database:
    type: "mysql"
    host: "127.0.0.1"
    name: "tsc2020-dev"
    user: "usr_tsc2020_dev_importer"
    password: "$=5SZEXjKbgF7#t%"




# database:
#     type: "mssql"
#     host: "MARR2\\GMARRMSSQL1"
#     name: "GeosTradingCards"
#     user: "Urgele1"
#     password: "goldmOOn78!"
#     useSPROCS: true
#     SPROCS:
#         select:
#             manufacturer: "Manufacturer.Select"
#             cardset: "CardSet.Select"
#             card: "Card.Select"
#             team: "Team.Select"
#             playerposition: "PlayerPosition.Select"
#         insert:
#             manufacturer: "Manufacturer.Insert"
#             cardset: "CardSet.Insert"
#             card: "Card.Insert"
#             team: "Team.Insert"
#             playerposition: "PlayerPosition.Insert"

