# database:
#     type: "mysql"
#     host: "127.0.0.1"
#     name: "tsc2020-dev"
#     user: "usr_tsc2020_dev_importer"
#     password: "$=5SZEXjKbgF7#t%"




database:
    type: "mssql"
    host: "MARR2\\GMARRMSSQL1"
    name: "GeosTradingCards-DEV"
    user: "Urgele1"
    password: "goldmOOn78!"
    useSPROCS: true
    SPROCS:
        select:
            manufacturer: "Manufacturer.Select"
            cardset: "CardSet.Select"
            subset: "Subset.Select"
            card: "Card.Select"
            team: "Team.Select"
            playerposition: "PlayerPosition.Select"
            attributes: "Attributes.Select"
            gradingclass: "GradingClass.Select"
        insert:
            manufacturer: "Manufacturer.Insert"
            cardset: "CardSet.Insert"
            subset: "Subset.Insert"
            card: "Card.Insert"
            team: "Team.Insert"
            playerposition: "PlayerPosition.Insert"
            attributes: "Attributes.Insert"
            card_has_attributes: "Card_Has_Attributes.Insert"
            cardvalue: "CardValue.Insert"
            singlecard: "SingleCard.Insert"
            singlecardgrading: "SingleCardGrading.Insert"
            gradingclass: "GradingClass.Insert"
