set_details_rows:
  - 'Season'
  - 'Manufacturer'
  - 'Set'
  - 'Insert Set'
  - 'Size'
  - 'Rarity'
  - 'Grading Modifier'
  - 'Comments'

set_contents_columns:
  - 'ID'
  - '#'
  - 'Name / Description'
  - 'RC'
  - 'Team'
  - 'Position'
  - 'LOW'
  - 'HIGH'
  - 'SELL'
  - 'Condition'
  - 'Subset'
  - 'Rarity'
  - 'Grading'
  - 'Cost'
  - 'Status'
  - 'Comments'

set_notes_rows:
  - 'Last Value Update'
  - 'Last Inventory Check'
  - 'Last Published To Google Docs'
  - 'Pricing Source'
  - 'Beckett.com Last Update'