//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTradingCards.Shop
{


    public partial class Grading
    {

        /// <summary>
        /// leftMenuCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeoTradingCards.Controls.LeftMenuMain leftMenuCtrl;

        /// <summary>
        /// medRect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeoTradingCards.Controls.Advertising.MedRectangleROS medRect;

        /// <summary>
        /// shopFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GeoTradingCards.Controls.ShopFooter shopFooter;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GeoTradingCards.Main Master
        {
            get
            {
                return ((GeoTradingCards.Main)(base.Master));
            }
        }
    }
}
