<?xml version="1.0" encoding="utf-8"?><Database Name="CardCollection" Class="ExceptionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\CardCollection.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CardCollectionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Exceptions" Member="Exceptions">
    <Type Name="Exception">
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="StackTrace" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="InnerException" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CustomMessage" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
</Database>